config/routes.rb
PublicVoid::Application.routes.draw do
  resources :users
  resources :sessions, only: [:new, :create, :destroy]
  resources :asset_transfers
  root  'static_pages#home'
  match '/signup',  to: 'users#new',            via: 'get'
  match '/signin',  to: 'sessions#new',         via: 'get'
  match '/signout', to: 'sessions#destroy',     via: 'delete'
  match '/help',    to: 'static_pages#help',    via: 'get'

end

app/models/asset_transfer.rb
class AssetTransfer < ActiveRecord::Base
  
  # Environment-specific direct upload url verifier screens for malicious posted upload locations.
  DIRECT_UPLOAD_URL_FORMAT = %r{\Ahttps:\/\/s3\.amazonaws\.com\/Composition#{!Rails.env.production? ? "\\-#{Rails.env}" : ''}\/(?<path>uploads\/.+\/(?<filename>.+))\z}.freeze
  
  belongs_to :user
  has_attached_file :upload
  
  validates :user_id, presence: true
  validates :direct_upload_url, presence: true, format: { with: DIRECT_UPLOAD_URL_FORMAT }
  
    
  before_create :set_upload_attributes
  after_commit :queue_processing
  
  # Store an unescaped version of the escaped URL that Amazon returns from direct upload.
  def direct_upload_url=(escaped_url)
    write_attribute(:direct_upload_url, (CGI.unescape(escaped_url) rescue nil))
  end
  
  # Determines if file requires post-processing (image resizing, etc)
  def post_process_required?
    %r{^(image|(x-)?application)/(bmp|gif|jpeg|jpg|pjpeg|png|x-png)$}.match(upload_content_type).present?
  end
  
  # Final upload processing step
  def self.transfer_and_cleanup(id)
    asset_transfer = AssetTransfer.find(id)
    direct_upload_url_data = DIRECT_UPLOAD_URL_FORMAT.match(asset_transfer.direct_upload_url)
    s3 = AWS::S3.new
    
    if asset_transfer.post_process_required?
      asset_transfer.upload = URI.parse(URI.escape(asset_transfer.direct_upload_url))
    else
      paperclip_file_path = "asset_transfers/uploads/#{id}/original/#{direct_upload_url_data[:filename]}"
      s3.buckets[Rails.configuration.aws[:bucket]].objects[paperclip_file_path].copy_from(direct_upload_url_data[:filepath])
    end
 
    asset_transfer.processed = true
    asset_transfer.save
    
    s3.buckets[Rails.configuration.aws[:bucket]].objects[direct_upload_url_data[:filepath]].delete
  end
      
  private
  
  # Set attachment attributes from the direct upload
  # @note Retry logic handles S3 "eventual consistency" lag.
  def set_upload_attributes
    tries ||= 5
    direct_upload_url_data = DIRECT_UPLOAD_URL_FORMAT.match(direct_upload_url)
    s3 = AWS::S3.new
    direct_upload_head = s3.buckets[Rails.configuration.aws[:bucket]].objects[direct_upload_url_data[:filepath]].head
 
    self.upload_file_name     = direct_upload_url_data[:filename]
    self.upload_file_size     = direct_upload_head.content_length
    self.upload_content_type  = direct_upload_head.content_type
    self.upload_updated_at    = direct_upload_head.last_modified
  rescue AWS::S3::Errors::NoSuchKey => e
    tries -= 1
    if tries > 0
      sleep(3)
      retry
    else
      false
    end
  end
  
  # Queue file processing
  def queue_processing
    AssetTransfer.delay.transfer_and_cleanup(id)
  end
end

app/controllers/asset_transfers_controller.rb
class AssetTransfersController < ApplicationController
  before_action :signed_in_user, :set_asset_transfer, only: [:show, :edit, :update, :destroy] 


  # GET /asset_transfers
  # GET /asset_transfers.json
  def index
    @asset_transfers = AssetTransfer.all
  end
  
  # GET /asset_transfers/1
  # GET /asset_transfers/1.json
  def show
  end
  
  # GET /asset_transfers/new
  def new
    @asset_transfer = AssetTransfer.new
  end

  # GET /asset_transfers/1/edit
  def edit
  end
  
  # PATCH/PUT /asset_transfers/1
  # PATCH/PUT /asset_transfers/1.json
  def update
    respond_to do |format|
      if @asset_transfer.update(asset_transfer_params)
        format.html { redirect_to @asset_transfer, notice: 'Upload was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @asset_transfer.errors, status: :unprocessable_entity }
      end
    end
  end
 
  # POST /asset_transfers
  # POST /asset_transfers.json
  def create
    @asset_transfer = current_user.asset_transfers.create(asset_transfer_params)
    if @asset_transfer.save
      flash[:success] = "Your asset is transferred into the void!"
      redirect_to root_url
    else
      render 'static_pages/home'
    end
  end

  # DELETE /asset_transfers/1
  # DELETE /asset_transfers/1.json
  def destroy
    @asset_transfer.destroy
    respond_to do |format|
      format.html { redirect_to asset_transfers_url }
      format.json { head :no_content }
    end
  end
  
  private
    
    def set_asset_transfer
      @asset_transfer = AssetTransfer.find(params[:id])
    end

 
    def asset_transfer_params
      params.require(:asset_transfer).permit(:upload )
    end
end  

app/views/asset_transfers/create.js.erb
<% if @asset_transfer.persisted? %>
  $('#upload_<%=params[:unique_id]%>').hide();
<% else %>
  $('#upload_<%=params[:unique_id]%> div.progress').removeClass('active progress-striped').addClass('progress-danger');
<% end %>

app/views/asset_transfers/edit.html.erb
<% provide(:title, 'Edit Transfers') %>
<h1>Edit Your Transfers</h1>

<%= render 'shared/transfer_form' %>

<%= link_to 'Show', @asset_transfer %> 
<%= link_to 'Back', @asset_transfers_path %>

app/views/asset_transfers/index.html.erb
<%= s3_uploader_form callback_url: asset_transfers_url, 
	callback_param: "asset_transfer[direct_upload_url]", 
	id: "s3-uploader" do %>
  <%= hidden_field_tag  "content-type", "" %>
  <%= file_field_tag :file, multiple: true %>
  <%= submit_tag "Submit!", class: "btn btn-large btn-primary" %>
<% end %>


<div id="uploads_container"></div>
<script id="template-upload" type="text/x-tmpl">
<div id="upload_{%=o.unique_id%}" class="upload">
  <h5>{%=o.name%}</h5>
  <div class="progress progress-striped active"><div class="bar" style="width: 0%"></div></div>
</div>
</script>

app/views/asset_transfers/new.html.erb
<h1>New Asset Transfer</h1>

<%= render 'shared/transfer_form' %>

<%= link_to 'Back', asset_transfers_path %>

app/views/asset_transfers/show.html.erb
<p id="notice"><%= notice %></p>

<br />
<%= render 'shared/transfer_form' %>
<br />

<%= link_to 'Edit', edit_asset_transfer_path(@asset_transfer) %> |
<%= link_to 'Back', asset_transfers_path %>